<?php
declare(strict_types=1);

$NOTICIAS_INICIAIS = [
    [
        'id' => 1,
        'titulo' => 'Prefeitura inaugura nova praça no bairro Centro',
        'categoria' => 'Cidade',
        'imagem' => 'https://images.unsplash.com/photo-1472653816316-3ad6f10a6592?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Espaco de lazer conta com academia ao ar livre e iluminacao em LED.',
        'conteudo' => 'A nova praca foi inaugurada na noite de ontem e recebeu moradores de varios bairros. Segundo a prefeitura, a obra faz parte de um pacote de melhorias urbanas.',
        'data' => '07/05/2026',
        'autor' => 'Redacao Local',
    ],
    [
        'id' => 2,
        'titulo' => 'Feira de produtores locais movimenta economia no fim de semana',
        'categoria' => 'Economia',
        'imagem' => 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Evento reuniu mais de 60 expositores da regiao.',
        'conteudo' => 'A feira teve artesanato, alimentos e musica ao vivo. Comerciantes relataram aumento nas vendas e defendem que o evento aconteca todo mes.',
        'data' => '06/05/2026',
        'autor' => 'Equipe Noticias',
    ],
    [
        'id' => 3,
        'titulo' => 'Escola municipal abre inscricoes para curso de robotica',
        'categoria' => 'Educacao',
        'imagem' => 'https://images.unsplash.com/photo-1581092335397-9583eb92d232?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Alunos do ensino fundamental podem participar gratuitamente.',
        'conteudo' => 'As aulas comecam no proximo mes e terao turmas no periodo da tarde. A iniciativa busca aproximar os estudantes da tecnologia.',
        'data' => '05/05/2026',
        'autor' => 'Maria Souza',
    ],
    [
        'id' => 4,
        'titulo' => 'Posto de saude amplia horario de atendimento',
        'categoria' => 'Saude',
        'imagem' => 'https://images.unsplash.com/photo-1579684453423-f84349ef60b0?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Unidade passa a funcionar ate as 21h em dias uteis.',
        'conteudo' => 'A secretaria de saude informou que o novo horario atende pedidos da comunidade. O objetivo e reduzir filas e facilitar consultas para quem trabalha em horario comercial.',
        'data' => '04/05/2026',
        'autor' => 'Joao Pedro',
    ],
    [
        'id' => 5,
        'titulo' => 'Time da cidade vence campeonato regional sub-20',
        'categoria' => 'Esporte',
        'imagem' => 'https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Final terminou em 2 a 1 com estadio lotado.',
        'conteudo' => 'A equipe conquistou o titulo inedito e foi recebida com festa pelos torcedores. A diretoria anunciou investimento na base para a proxima temporada.',
        'data' => '03/05/2026',
        'autor' => 'Carlos Lima',
    ],
    [
        'id' => 6,
        'titulo' => 'Obras na Avenida Central causam desvios de transito',
        'categoria' => 'Cidade',
        'imagem' => 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Trecho entre as ruas 7 e 12 fica interditado por 30 dias para recape do asfalto.',
        'conteudo' => 'A Secretaria de Obras informou que os trabalhos de recapeamento da Avenida Central terao inicio na proxima segunda-feira. O trecho compreendido entre as ruas 7 e 12 ficara fechado ao trafego por aproximadamente 30 dias. Motoristas devem utilizar as vias alternativas pela Rua das Palmeiras e pela Estrada do Contorno. Agentes de transito estarao presentes nos principais cruzamentos para orientar os condutores.',
        'data' => '02/05/2026',
        'autor' => 'Redacao Local',
    ],
    [
        'id' => 7,
        'titulo' => 'Campanha de vacinacao contra gripe comeca na proxima semana',
        'categoria' => 'Saude',
        'imagem' => 'https://images.unsplash.com/photo-1584118624012-df056829fbd0?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Criancas, idosos e gestantes sao o publico prioritario nesta primeira fase.',
        'conteudo' => 'A Secretaria Municipal de Saude divulgou o calendario da campanha de vacinacao contra a gripe. A primeira fase, prevista para iniciar na segunda-feira, atende criancas de seis meses a cinco anos, idosos acima de 60 anos e gestantes. A vacinacao sera realizada em todos os postos de saude do municipio, de segunda a sexta, das 8h as 17h. Nao e necessario agendamento. A meta e vacinar 90% do publico-alvo ate o fim de maio.',
        'data' => '01/05/2026',
        'autor' => 'Ana Paula Ferreira',
    ],
    [
        'id' => 8,
        'titulo' => 'Biblioteca municipal ganha novo acervo com mais de 2 mil livros',
        'categoria' => 'Educacao',
        'imagem' => 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Doacao inclui colecoes de literatura brasileira, ciencias e paradidaticos para o ensino medio.',
        'conteudo' => 'A Biblioteca Municipal recebeu uma doacao de 2.300 livros feita por uma empresa local em parceria com a prefeitura. O acervo inclui obras de literatura brasileira contemporanea, livros de ciencias naturais e uma colecao completa de paradidaticos voltada ao ensino medio. Os titulos ja estao catalogados e disponiveis para emprestimo. A biblioteca funciona de segunda a sabado, das 9h as 18h, e o cadastro para emprestimo e gratuito.',
        'data' => '30/04/2026',
        'autor' => 'Bruno Cavalcante',
    ],
    [
        'id' => 9,
        'titulo' => 'Novo terminal de onibus deve reduzir tempo de espera em ate 40%',
        'categoria' => 'Cidade',
        'imagem' => 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Obra esta 70% concluida e previsao de entrega e para o mes de julho.',
        'conteudo' => 'O novo terminal de onibus do bairro Jardim das Acaias esta com 70% das obras concluidas, segundo a prefeitura. O projeto conta com 12 plataformas cobertas, banheiros acessiveis, sala de espera climatizada e painel digital com informacoes em tempo real sobre os horarios. A expectativa e de que o terminal reduza em ate 40% o tempo de espera dos passageiros. A inauguracao esta prevista para julho deste ano.',
        'data' => '28/04/2026',
        'autor' => 'Marcos Andrade',
    ],
    [
        'id' => 10,
        'titulo' => 'Agricultores da regiao relatam prejuizos apos periodo de seca',
        'categoria' => 'Economia',
        'imagem' => 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Producao de hortalicas caiu quase 30% em comparacao ao mesmo periodo do ano anterior.',
        'conteudo' => 'Produtores rurais da regiao registraram queda de quase 30% na producao de hortalicas apos o longo periodo de estiagem que atingiu o municipio em abril. A Secretaria de Agricultura informou que esta articulando junto ao governo estadual a liberacao de credito emergencial para os agricultores mais afetados. Tecnicos da pasta visitaram as propriedades esta semana para levantar os dados dos prejuizos e orientar sobre tecnicas de irrigacao mais eficientes.',
        'data' => '27/04/2026',
        'autor' => 'Fernanda Costa',
    ],
    [
        'id' => 11,
        'titulo' => 'Projeto social ensina programacao a jovens em vulnerabilidade',
        'categoria' => 'Educacao',
        'imagem' => 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Iniciativa atende 80 alunos entre 14 e 19 anos e ja garantiu emprego para oito deles.',
        'conteudo' => 'O projeto Codigo Livre, mantido por uma ONG local em parceria com empresas de tecnologia, ja atendeu 80 jovens em situacao de vulnerabilidade social neste ano. O curso e gratuito, tem duracao de seis meses e cobre logica de programacao, desenvolvimento web basico e preparacao para o mercado de trabalho. Oito alunos das turmas anteriores ja foram contratados por empresas da cidade. As inscricoes para a proxima turma estao abertas ate o dia 15 de maio.',
        'data' => '26/04/2026',
        'autor' => 'Rafael Monteiro',
    ],
    [
        'id' => 12,
        'titulo' => 'Parque ecologico recebe trilha acessivel para pessoas com deficiencia',
        'categoria' => 'Cidade',
        'imagem' => 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
        'resumo' => 'Nova trilha de 800 metros conta com piso tatil, corrimao e placas em braile.',
        'conteudo' => 'O Parque Ecologico Municipal ganhou uma trilha de 800 metros totalmente adaptada para pessoas com deficiencia fisica e visual. O percurso conta com piso tatil, corrimao em toda a extensao, rampas de acesso e placas informativas em braile e com QR Code para audioguia. A obra foi financiada com recursos federais e custou R$ 420 mil. A inauguracao contou com a presenca de representantes de associacoes de pessoas com deficiencia, que participaram do processo de planejamento da trilha.',
        'data' => '25/04/2026',
        'autor' => 'Camila Nunes',
    ],
];

$CREDENCIAIS_FIXAS = [
    'usuario' => 'admin',
    'senha_hash' => password_hash('123456', PASSWORD_DEFAULT),
];
